//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.04 at 09:21:47 PM CEST 
//


package nth.meyn.cx.sysmac.converter.sysmac.ladder.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RungsRungXMLLadderElementPinViewModel_QNAME = new QName("", "PinViewModel");
    private final static QName _RungsRungXMLLadderElementConnectionPoint_QNAME = new QName("", "ConnectionPoint");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Rungs }
     * 
     */
    public Rungs createRungs() {
        return new Rungs();
    }

    /**
     * Create an instance of {@link Rungs.RungXML }
     * 
     */
    public Rungs.RungXML createRungsRungXML() {
        return new Rungs.RungXML();
    }

    /**
     * Create an instance of {@link Rungs.RungXML.LadderElement }
     * 
     */
    public Rungs.RungXML.LadderElement createRungsRungXMLLadderElement() {
        return new Rungs.RungXML.LadderElement();
    }

    /**
     * Create an instance of {@link Rungs.RungXML.LadderElement.ConnectionPoint }
     * 
     */
    public Rungs.RungXML.LadderElement.ConnectionPoint createRungsRungXMLLadderElementConnectionPoint() {
        return new Rungs.RungXML.LadderElement.ConnectionPoint();
    }

    /**
     * Create an instance of {@link Rungs.RungXML.LadderElement.PinViewModel }
     * 
     */
    public Rungs.RungXML.LadderElement.PinViewModel createRungsRungXMLLadderElementPinViewModel() {
        return new Rungs.RungXML.LadderElement.PinViewModel();
    }

    /**
     * Create an instance of {@link Rungs.RungXML.LadderElement.ConnectionPoint.Edge }
     * 
     */
    public Rungs.RungXML.LadderElement.ConnectionPoint.Edge createRungsRungXMLLadderElementConnectionPointEdge() {
        return new Rungs.RungXML.LadderElement.ConnectionPoint.Edge();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Rungs.RungXML.LadderElement.PinViewModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PinViewModel", scope = Rungs.RungXML.LadderElement.class)
    public JAXBElement<Rungs.RungXML.LadderElement.PinViewModel> createRungsRungXMLLadderElementPinViewModel(Rungs.RungXML.LadderElement.PinViewModel value) {
        return new JAXBElement<Rungs.RungXML.LadderElement.PinViewModel>(_RungsRungXMLLadderElementPinViewModel_QNAME, Rungs.RungXML.LadderElement.PinViewModel.class, Rungs.RungXML.LadderElement.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Rungs.RungXML.LadderElement.ConnectionPoint }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ConnectionPoint", scope = Rungs.RungXML.LadderElement.class)
    public JAXBElement<Rungs.RungXML.LadderElement.ConnectionPoint> createRungsRungXMLLadderElementConnectionPoint(Rungs.RungXML.LadderElement.ConnectionPoint value) {
        return new JAXBElement<Rungs.RungXML.LadderElement.ConnectionPoint>(_RungsRungXMLLadderElementConnectionPoint_QNAME, Rungs.RungXML.LadderElement.ConnectionPoint.class, Rungs.RungXML.LadderElement.class, value);
    }

}
