package nth.meyn.innovation.intake.dom.capitalsalesintake;

public enum OrderLineType {
ORDER, INTAKE_OLD_PRODUCTS, INTAKE_NEW_PRODUCTS, INTAKE_FORECAST_NEW_PRODUCTS, INTAKE_FORECAST_PRODUCTS_IN_PIPELINE, INTAKE_FORECAST_PRODUCTS_IN_ROADMAP
}
