package nth.innoforce.domain.product.group;


public enum ProductGroup  {
	LIVE_BIRD_HANDLING,
	SLAUGHTERING,
	EVISCERATION,
	CHILLING,
	CUT_UP,
	DEBONING,
	WEIGHING_AND_GRADING,
	LOGISTICS_AND_PACKAGING,
	MONITORING_AND_CONTROL,
	OFFAL_AND_BY_PRODUCT_HANDLING
}
