//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.02 at 08:22:12 PM CEST 
//


package nth.meyn.cx.sysmac.converter.cx.ladder.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  RandomGenerator methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LadderDiagramRungListRUNGElementListCOIL_QNAME = new QName("", "COIL");
    private final static QName _LadderDiagramRungListRUNGElementListINSTRUCTION_QNAME = new QName("", "INSTRUCTION");
    private final static QName _LadderDiagramRungListRUNGElementListCONTACT_QNAME = new QName("", "CONTACT");
    private final static QName _LadderDiagramRungListRUNGElementListFBPARAMETER_QNAME = new QName("", "FBPARAMETER");
    private final static QName _LadderDiagramRungListRUNGElementListVERTICAL_QNAME = new QName("", "VERTICAL");
    private final static QName _LadderDiagramRungListRUNGElementListHORIZONTAL_QNAME = new QName("", "HORIZONTAL");
    private final static QName _LadderDiagramRungListRUNGElementListFB_QNAME = new QName("", "FB");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CxLadderDiagram }
     * 
     */
    public CxLadderDiagram createLadderDiagram() {
        return new CxLadderDiagram();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList }
     * 
     */
    public CxLadderDiagram.RungList createLadderDiagramRungList() {
        return new CxLadderDiagram.RungList();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG }
     * 
     */
    public CxLadderDiagram.RungList.RUNG createLadderDiagramRungListRUNG() {
        return new CxLadderDiagram.RungList.RUNG();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG.ElementList }
     * 
     */
    public CxLadderDiagram.RungList.RUNG.ElementList createLadderDiagramRungListRUNGElementList() {
        return new CxLadderDiagram.RungList.RUNG.ElementList();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG.ElementList.COIL }
     * 
     */
    public CxLadderDiagram.RungList.RUNG.ElementList.COIL createLadderDiagramRungListRUNGElementListCOIL() {
        return new CxLadderDiagram.RungList.RUNG.ElementList.COIL();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG.ElementList.COIL.Operands }
     * 
     */
    public CxLadderDiagram.RungList.RUNG.ElementList.COIL.Operands createLadderDiagramRungListRUNGElementListCOILOperands() {
        return new CxLadderDiagram.RungList.RUNG.ElementList.COIL.Operands();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG.ElementList.FBPARAMETER }
     * 
     */
    public CxLadderDiagram.RungList.RUNG.ElementList.FBPARAMETER createLadderDiagramRungListRUNGElementListFBPARAMETER() {
        return new CxLadderDiagram.RungList.RUNG.ElementList.FBPARAMETER();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG.ElementList.FBPARAMETER.Operands }
     * 
     */
    public CxLadderDiagram.RungList.RUNG.ElementList.FBPARAMETER.Operands createLadderDiagramRungListRUNGElementListFBPARAMETEROperands() {
        return new CxLadderDiagram.RungList.RUNG.ElementList.FBPARAMETER.Operands();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG.ElementList.FB }
     * 
     */
    public CxLadderDiagram.RungList.RUNG.ElementList.FB createLadderDiagramRungListRUNGElementListFB() {
        return new CxLadderDiagram.RungList.RUNG.ElementList.FB();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG.ElementList.FB.Operands }
     * 
     */
    public CxLadderDiagram.RungList.RUNG.ElementList.FB.Operands createLadderDiagramRungListRUNGElementListFBOperands() {
        return new CxLadderDiagram.RungList.RUNG.ElementList.FB.Operands();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG.ElementList.CONTACT }
     * 
     */
    public CxLadderDiagram.RungList.RUNG.ElementList.CONTACT createLadderDiagramRungListRUNGElementListCONTACT() {
        return new CxLadderDiagram.RungList.RUNG.ElementList.CONTACT();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG.ElementList.CONTACT.Operands }
     * 
     */
    public CxLadderDiagram.RungList.RUNG.ElementList.CONTACT.Operands createLadderDiagramRungListRUNGElementListCONTACTOperands() {
        return new CxLadderDiagram.RungList.RUNG.ElementList.CONTACT.Operands();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG.ElementList.INSTRUCTION }
     * 
     */
    public CxLadderDiagram.RungList.RUNG.ElementList.INSTRUCTION createLadderDiagramRungListRUNGElementListINSTRUCTION() {
        return new CxLadderDiagram.RungList.RUNG.ElementList.INSTRUCTION();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG.ElementList.INSTRUCTION.Operands }
     * 
     */
    public CxLadderDiagram.RungList.RUNG.ElementList.INSTRUCTION.Operands createLadderDiagramRungListRUNGElementListINSTRUCTIONOperands() {
        return new CxLadderDiagram.RungList.RUNG.ElementList.INSTRUCTION.Operands();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG.ElementList.HORIZONTAL }
     * 
     */
    public CxLadderDiagram.RungList.RUNG.ElementList.HORIZONTAL createLadderDiagramRungListRUNGElementListHORIZONTAL() {
        return new CxLadderDiagram.RungList.RUNG.ElementList.HORIZONTAL();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG.ElementList.VERTICAL }
     * 
     */
    public CxLadderDiagram.RungList.RUNG.ElementList.VERTICAL createLadderDiagramRungListRUNGElementListVERTICAL() {
        return new CxLadderDiagram.RungList.RUNG.ElementList.VERTICAL();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG.ElementList.VERTICAL.Operands }
     * 
     */
    public CxLadderDiagram.RungList.RUNG.ElementList.VERTICAL.Operands createLadderDiagramRungListRUNGElementListVERTICALOperands() {
        return new CxLadderDiagram.RungList.RUNG.ElementList.VERTICAL.Operands();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG.ElementList.COIL.Operands.Operand }
     * 
     */
    public CxLadderDiagram.RungList.RUNG.ElementList.COIL.Operands.Operand createLadderDiagramRungListRUNGElementListCOILOperandsOperand() {
        return new CxLadderDiagram.RungList.RUNG.ElementList.COIL.Operands.Operand();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG.ElementList.FBPARAMETER.Operands.Operand }
     * 
     */
    public CxLadderDiagram.RungList.RUNG.ElementList.FBPARAMETER.Operands.Operand createLadderDiagramRungListRUNGElementListFBPARAMETEROperandsOperand() {
        return new CxLadderDiagram.RungList.RUNG.ElementList.FBPARAMETER.Operands.Operand();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG.ElementList.FB.Operands.Operand }
     * 
     */
    public CxLadderDiagram.RungList.RUNG.ElementList.FB.Operands.Operand createLadderDiagramRungListRUNGElementListFBOperandsOperand() {
        return new CxLadderDiagram.RungList.RUNG.ElementList.FB.Operands.Operand();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG.ElementList.CONTACT.Operands.Operand }
     * 
     */
    public CxLadderDiagram.RungList.RUNG.ElementList.CONTACT.Operands.Operand createLadderDiagramRungListRUNGElementListCONTACTOperandsOperand() {
        return new CxLadderDiagram.RungList.RUNG.ElementList.CONTACT.Operands.Operand();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG.ElementList.INSTRUCTION.Operands.Operand }
     * 
     */
    public CxLadderDiagram.RungList.RUNG.ElementList.INSTRUCTION.Operands.Operand createLadderDiagramRungListRUNGElementListINSTRUCTIONOperandsOperand() {
        return new CxLadderDiagram.RungList.RUNG.ElementList.INSTRUCTION.Operands.Operand();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG.ElementList.HORIZONTAL.Operands }
     * 
     */
    public CxLadderDiagram.RungList.RUNG.ElementList.HORIZONTAL.Operands createLadderDiagramRungListRUNGElementListHORIZONTALOperands() {
        return new CxLadderDiagram.RungList.RUNG.ElementList.HORIZONTAL.Operands();
    }

    /**
     * Create an instance of {@link CxLadderDiagram.RungList.RUNG.ElementList.VERTICAL.Operands.Operand }
     * 
     */
    public CxLadderDiagram.RungList.RUNG.ElementList.VERTICAL.Operands.Operand createLadderDiagramRungListRUNGElementListVERTICALOperandsOperand() {
        return new CxLadderDiagram.RungList.RUNG.ElementList.VERTICAL.Operands.Operand();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CxLadderDiagram.RungList.RUNG.ElementList.COIL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "COIL", scope = CxLadderDiagram.RungList.RUNG.ElementList.class)
    public JAXBElement<CxLadderDiagram.RungList.RUNG.ElementList.COIL> createLadderDiagramRungListRUNGElementListCOIL(CxLadderDiagram.RungList.RUNG.ElementList.COIL value) {
        return new JAXBElement<CxLadderDiagram.RungList.RUNG.ElementList.COIL>(_LadderDiagramRungListRUNGElementListCOIL_QNAME, CxLadderDiagram.RungList.RUNG.ElementList.COIL.class, CxLadderDiagram.RungList.RUNG.ElementList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CxLadderDiagram.RungList.RUNG.ElementList.INSTRUCTION }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "INSTRUCTION", scope = CxLadderDiagram.RungList.RUNG.ElementList.class)
    public JAXBElement<CxLadderDiagram.RungList.RUNG.ElementList.INSTRUCTION> createLadderDiagramRungListRUNGElementListINSTRUCTION(CxLadderDiagram.RungList.RUNG.ElementList.INSTRUCTION value) {
        return new JAXBElement<CxLadderDiagram.RungList.RUNG.ElementList.INSTRUCTION>(_LadderDiagramRungListRUNGElementListINSTRUCTION_QNAME, CxLadderDiagram.RungList.RUNG.ElementList.INSTRUCTION.class, CxLadderDiagram.RungList.RUNG.ElementList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CxLadderDiagram.RungList.RUNG.ElementList.CONTACT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CONTACT", scope = CxLadderDiagram.RungList.RUNG.ElementList.class)
    public JAXBElement<CxLadderDiagram.RungList.RUNG.ElementList.CONTACT> createLadderDiagramRungListRUNGElementListCONTACT(CxLadderDiagram.RungList.RUNG.ElementList.CONTACT value) {
        return new JAXBElement<CxLadderDiagram.RungList.RUNG.ElementList.CONTACT>(_LadderDiagramRungListRUNGElementListCONTACT_QNAME, CxLadderDiagram.RungList.RUNG.ElementList.CONTACT.class, CxLadderDiagram.RungList.RUNG.ElementList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CxLadderDiagram.RungList.RUNG.ElementList.FBPARAMETER }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FBPARAMETER", scope = CxLadderDiagram.RungList.RUNG.ElementList.class)
    public JAXBElement<CxLadderDiagram.RungList.RUNG.ElementList.FBPARAMETER> createLadderDiagramRungListRUNGElementListFBPARAMETER(CxLadderDiagram.RungList.RUNG.ElementList.FBPARAMETER value) {
        return new JAXBElement<CxLadderDiagram.RungList.RUNG.ElementList.FBPARAMETER>(_LadderDiagramRungListRUNGElementListFBPARAMETER_QNAME, CxLadderDiagram.RungList.RUNG.ElementList.FBPARAMETER.class, CxLadderDiagram.RungList.RUNG.ElementList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CxLadderDiagram.RungList.RUNG.ElementList.VERTICAL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VERTICAL", scope = CxLadderDiagram.RungList.RUNG.ElementList.class)
    public JAXBElement<CxLadderDiagram.RungList.RUNG.ElementList.VERTICAL> createLadderDiagramRungListRUNGElementListVERTICAL(CxLadderDiagram.RungList.RUNG.ElementList.VERTICAL value) {
        return new JAXBElement<CxLadderDiagram.RungList.RUNG.ElementList.VERTICAL>(_LadderDiagramRungListRUNGElementListVERTICAL_QNAME, CxLadderDiagram.RungList.RUNG.ElementList.VERTICAL.class, CxLadderDiagram.RungList.RUNG.ElementList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CxLadderDiagram.RungList.RUNG.ElementList.HORIZONTAL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HORIZONTAL", scope = CxLadderDiagram.RungList.RUNG.ElementList.class)
    public JAXBElement<CxLadderDiagram.RungList.RUNG.ElementList.HORIZONTAL> createLadderDiagramRungListRUNGElementListHORIZONTAL(CxLadderDiagram.RungList.RUNG.ElementList.HORIZONTAL value) {
        return new JAXBElement<CxLadderDiagram.RungList.RUNG.ElementList.HORIZONTAL>(_LadderDiagramRungListRUNGElementListHORIZONTAL_QNAME, CxLadderDiagram.RungList.RUNG.ElementList.HORIZONTAL.class, CxLadderDiagram.RungList.RUNG.ElementList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CxLadderDiagram.RungList.RUNG.ElementList.FB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FB", scope = CxLadderDiagram.RungList.RUNG.ElementList.class)
    public JAXBElement<CxLadderDiagram.RungList.RUNG.ElementList.FB> createLadderDiagramRungListRUNGElementListFB(CxLadderDiagram.RungList.RUNG.ElementList.FB value) {
        return new JAXBElement<CxLadderDiagram.RungList.RUNG.ElementList.FB>(_LadderDiagramRungListRUNGElementListFB_QNAME, CxLadderDiagram.RungList.RUNG.ElementList.FB.class, CxLadderDiagram.RungList.RUNG.ElementList.class, value);
    }

}
